### ISSUE TITLE
`EntityRelationRole.label` should be `InternationalizedLabel`

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/InTaVia-Backend#12]
i think `EntityRelationRole.label` should be `InternationalizedLabel`?

**Comment by sennierer** [comment]
Yes, I'll fix that.

**Comment by stefanprobst** [comment]
probably `MediaKind.label` as well? also `Gender`? - i guess that's a question for any enum?

**Comment by sennierer** [comment]
left MediaKind.label as it is now, as its a hardcoded enum in the model. I guess the value will be determined by the mime type of the file and wont come from the data. not sure we need internationalized labels for that
