### ISSUE TITLE
[question] clarify whether we need more complex shape on `Entity.linkedIds`

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/InTaVia-Backend#13]
can't quite remember what we discussed for `Entity.linkedIds` (and maybe also `Entity.alternativeLabels`) - do we need a way to express the name of the id service the linkedId points to? e.g. `linkedIds: ['123456789']` vs `linkedIds: [{ id: '123456789', provider: { id: 'isbn', label: 'ISBN' } }]`. or just `linkedIds: [{ id: '123456789', label: 'ISBN' }]`

**Comment by sennierer** [comment]
Good point. I think the latter is enough. IDs of the providers would be fake anyway
