### ISSUE TITLE
keep pagination in entities by id endpoint?

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/InTaVia-Backend#23]
see #22 
in the current implementation the endpoint returns the same shape as the search endpoint, including the pagination. This is obviously not really needed as it can only return 0 or 1 object. However, as the models could be reused, this was easier to implement.

**Comment by stefanprobst** [comment]
if `/api/entities/id` accepts a single `id` as query param, then yes pagination info should be removed.

**Comment by sennierer** [comment]
Good point, I'll refactor that to accept an array of ids.

Am 22. Juli 2022 16:03:15 MESZ schrieb stefanprobst ***@***.***>:
