### ISSUE TITLE
entityType search param should accept array

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/InTaVia-Backend#9]
according to the openapi docs, the `entityType` query param currently accepts an enum of entity type.

should allow querying multiple entity types.

![Screenshot_20220719_201009](https://user-images.githubusercontent.com/20753323/179819691-99592dcd-43b7-4396-a45b-9eb548ed9560.png)

**Comment by sennierer** [comment]
Thought about that, but given that at the moment the endpoint only returns persons and groups it was not needed. Is that important for generating the interfaces in the frontend? If not, I would leave it like that until places are correctly included.

**Comment by stefanprobst** [comment]
if it's complicated to implement server side it's fine to leave as is for now - just would save changing interfaces later.

**Comment by stefanprobst** [comment]
also, for consistency, should be renamed to `kind` ?
